// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgqq5MatZ-XtsK8qcDl6gAqMVwFJjSn-E',
    appId: '1:710632497382:web:39fef18b7d76a76af09b27',
    messagingSenderId: '710632497382',
    projectId: 'social-impact-mvp-prod-b6805',
    authDomain: 'social-impact-mvp-prod-b6805.firebaseapp.com',
    storageBucket: 'social-impact-mvp-prod-b6805.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFZxFtqyd0MQZDgC-gofKB5LuLLdkUoMU',
    appId: '1:710632497382:android:228a47ca36439a70f09b27',
    messagingSenderId: '710632497382',
    projectId: 'social-impact-mvp-prod-b6805',
    storageBucket: 'social-impact-mvp-prod-b6805.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC657gFElqjNDCXRZXkkVUSum7PysTjNb8',
    appId: '1:710632497382:ios:f139bc696b44badff09b27',
    messagingSenderId: '710632497382',
    projectId: 'social-impact-mvp-prod-b6805',
    storageBucket: 'social-impact-mvp-prod-b6805.firebasestorage.app',
    iosBundleId: 'com.example.socialImpactMvp',
  );
}
